import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Basic example using <code>multer</code> with Next.js api
        </h1>

        <p className={styles.description}>
          Use a tool like postman to upload a file to <code>/api/upload</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
